### ISSUE TITLE
Ask if you don't understand

### ISSUE THREAD

**Issue by cuihejia** [zhuokaizhao/PIV-LiteFlowNet-en-Pytorch#1]
Hello, can you tell me something about it json.load Is img1 and img2 corresponding? thank you

**Comment by zhuokaizhao** [comment]
I am not 100% sure if I understand your question, are you talking about this line below?
`img1_name_list = json.load(open(data_path + "/img1_name_list.json", 'r'))`
If so, it basically loads the images from the .json file that should be saved during the first run of this program (the `try: ` part in function `read_all(data_path)` in load_data.py). If it is the first run, the program will generate these .json files and save them for later use (the `except: ` part in function `read_all(data_path)` in load_data.py)

**Comment by cuihejia** [comment]
Thank you, I understand what you mean, thank you very much.
